#!/usr/bin/env python3
# GENERATED by scripts/generate_fmp_client.py — do not edit.
# Source of truth: scripts/fmp_client/ (core_template.py.tmpl, registry.py, extensions/).
# Regenerate: python3 scripts/generate_fmp_client.py
"""
FMP API Client for VCP Screener

Provides rate-limited access to Financial Modeling Prep API endpoints.

Features:
- Rate limiting (0.3s between requests)
- Automatic retry on 429 errors
- Session caching for duplicate requests
- Batch quote support
- S&P 500 constituents fetching
"""

import os
import sys
import time
from datetime import date, timedelta
from typing import Optional

try:
    import requests
except ImportError:
    print("ERROR: requests library not found. Install with: pip install requests", file=sys.stderr)
    sys.exit(1)

try:
    from _fmp_compat import v3_to_stable
except ModuleNotFoundError:  # loaded by file path (e.g. repo-level contract tests)
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from _fmp_compat import v3_to_stable

# --- FMP endpoint fallback: stable (new users) -> v3 (legacy users) ---


def _stable_quote_url(base, symbols_str, params):
    """stable/quote?symbol=^GSPC"""
    params["symbol"] = symbols_str
    return base, params


def _v3_quote_url(base, symbols_str, params):
    """api/v3/quote/^GSPC"""
    return f"{base}/{symbols_str}", params


def _stable_hist_url(base, symbols_str, params):
    """stable/historical-price-eod/full?symbol=^GSPC&from=...&to=..."""
    params["symbol"] = symbols_str
    # New stable EOD endpoint ignores `timeseries`; convert to from/to range
    # to bound the payload. Use 2x calendar days to cover N trading days
    # (trading-day/calendar-day ratio ~252/365 ~0.69, so *2 leaves headroom).
    days = params.pop("timeseries", None)
    if days is not None:
        today = date.today()
        params["from"] = (today - timedelta(days=int(days) * 2)).isoformat()
        params["to"] = today.isoformat()
    return base, params


def _v3_hist_url(base, symbols_str, params):
    """api/v3/historical-price-full/^GSPC?timeseries=80"""
    return f"{base}/{symbols_str}", params


_FMP_ENDPOINTS = {
    "quote": [
        ("https://financialmodelingprep.com/stable/quote", _stable_quote_url),
        ("https://financialmodelingprep.com/api/v3/quote", _v3_quote_url),
    ],
    "historical": [
        ("https://financialmodelingprep.com/stable/historical-price-eod/full", _stable_hist_url),
        ("https://financialmodelingprep.com/api/v3/historical-price-full", _v3_hist_url),
    ],
}


def _normalize_eod_flat_list(data, symbols_str: str, limit: Optional[int] = None):
    """Convert stable/historical-price-eod/full flat list to v3-compatible dict.

    Input  : [{"symbol": "SPY", "date": "...", "open": ..., ...}, ...]
    Output : {"symbol": "SPY", "historical": [{"date": ..., "open": ..., ...}, ...]}

    Returns the input unchanged if not a list (passthrough for v3 dict /
    historicalStockList responses). Returns None when no row matches the
    requested symbol; the caller will record the failure and try the next
    endpoint.

    If `limit` is provided (the original `timeseries=N` request), the
    `historical` list is truncated to the first `limit` entries. The new
    EOD endpoint ignores `timeseries` and returns the full available history,
    so the caller's date-range bounding plus this truncation together preserve
    the legacy "most-recent N rows" contract. Truncation assumes descending
    date order, which the FMP EOD endpoint provides (verified live).

    Note: empty list ``[]`` does not reach this normalizer because the caller's
    ``if not data: continue`` falsy check handles it earlier in
    ``_request_with_fallback``.
    """
    if not isinstance(data, list):
        return data
    if not data:
        return None
    norm_target = symbols_str.replace("-", ".")
    matched_symbol = None
    historical = []
    for row in data:
        if not isinstance(row, dict):
            continue
        # Be permissive: single-symbol endpoint may omit per-row "symbol".
        # Treat missing symbol as belonging to the requested symbols_str.
        row_sym = row.get("symbol") or symbols_str
        if row_sym.replace("-", ".") != norm_target:
            continue
        matched_symbol = matched_symbol or row_sym
        historical.append({k: v for k, v in row.items() if k != "symbol"})
    if not historical:
        return None
    if limit is not None and limit > 0:
        historical = historical[:limit]
    return {"symbol": matched_symbol or symbols_str, "historical": historical}


# --- yfinance fallback (free, no API key) for FMP free-tier 402/403 ---
# FMP's free tier no longer serves the legacy quote / historical endpoints
# (HTTP 402/403 after the 2025-08-31 cutoff). yfinance supplies the same
# OHLCV data with no key, so we transparently fall back to it and reshape the
# result into the v3-compatible dicts the screener already expects.

_YF_AVAILABLE = None
_yf_hist_cache: dict = {}


def _yf_ok() -> bool:
    global _YF_AVAILABLE
    if _YF_AVAILABLE is None:
        try:
            import yfinance  # noqa: F401

            _YF_AVAILABLE = True
        except Exception:
            _YF_AVAILABLE = False
    return _YF_AVAILABLE


# yfinance writes a US share class with a dash (BRK.B -> BRK-B) but keeps the dot
# for an exchange suffix (SAP.DE, VOD.L). A blanket dot->dash swap therefore turns
# every non-US ticker into a symbol Yahoo has never heard of, and the screen comes
# back empty for the whole universe. Only swap when the trailing token is NOT a
# known exchange code. Share-class letters (A/B/C/...) are deliberately absent.
_YF_EXCHANGE_SUFFIXES = {
    "L", "DE", "AS", "HE", "PA", "BR", "MI", "MC", "VI", "LS", "IR", "SW",
    "ST", "OL", "CO", "T", "HK", "AX", "TO", "NZ", "SI", "KS", "KQ", "TW",
    "SA", "MX", "BO", "NS", "IS", "F", "BE", "DU", "HM", "MU", "SG", "WA",
    "PR", "AT", "TA", "JO", "CN", "NE", "VX", "OQ",
}


def _yf_sym(symbol: str) -> str:
    """Translate an internal symbol into the form yfinance expects."""
    head, sep, tail = symbol.rpartition(".")
    if sep and tail.upper() in _YF_EXCHANGE_SUFFIXES:
        return symbol
    return symbol.replace(".", "-")


def _yf_fetch_history(symbol: str, days: int) -> Optional[list]:
    """Fetch OHLCV via yfinance as v3-shaped rows (most-recent-first), or None."""
    if not _yf_ok():
        return None
    key = (symbol, days)
    if key in _yf_hist_cache:
        return _yf_hist_cache[key]
    import yfinance as yf

    yf_symbol = _yf_sym(symbol)
    # `days` is trading bars; scale to calendar days (~252/yr) with headroom.
    # A fixed "2y" silently truncated --history 1260 to 502 bars while the
    # report still claimed scan_days=1260.
    period_days = max(int(days * 1.6) + 15, 400) if days else 400
    try:
        df = yf.Ticker(yf_symbol).history(period=f"{period_days}d", auto_adjust=False)
    except Exception:
        _yf_hist_cache[key] = None
        return None
    if df is None or df.empty:
        _yf_hist_cache[key] = None
        return None
    if "Close" not in df.columns:  # same malformed-frame guard as _df_to_rows
        _yf_hist_cache[key] = None
        return None
    df = df.dropna(subset=["Close"])  # drop partial/empty trailing rows (yfinance quirk)
    if df.empty:
        _yf_hist_cache[key] = None
        return None
    rows = []
    for idx, r in df.iterrows():
        try:
            close = float(r["Close"])
            rows.append(
                {
                    "date": idx.strftime("%Y-%m-%d"),
                    "open": float(r["Open"]),
                    "high": float(r["High"]),
                    "low": float(r["Low"]),
                    "close": close,
                    "adjClose": float(r["Adj Close"]) if "Adj Close" in r else close,
                    "volume": float(r["Volume"]),
                }
            )
        except Exception:
            continue
    rows.reverse()  # yfinance is oldest-first; v3 contract is most-recent-first
    if days and days > 0:
        rows = rows[:days]
    result = rows or None
    _yf_hist_cache[key] = result
    return result


def _df_to_rows(df, days: int) -> Optional[list]:
    """Shared v3-shaping for a single-ticker yfinance frame."""
    if df is None or df.empty:
        return None
    # A throttled ticker inside a multi-ticker download comes back as a frame with
    # no OHLCV columns at all, and dropna(subset=["Close"]) raises KeyError on it
    # rather than returning empty -- which killed the whole 1001-name run. Treat it
    # as a miss so the caller leaves it uncached for the per-symbol retry.
    if "Close" not in df.columns:
        return None
    df = df.dropna(subset=["Close"])  # drop partial/empty trailing rows (yfinance quirk)
    if df.empty:
        return None
    rows = []
    for idx, r in df.iterrows():
        try:
            close = float(r["Close"])
            rows.append(
                {
                    "date": idx.strftime("%Y-%m-%d"),
                    "open": float(r["Open"]),
                    "high": float(r["High"]),
                    "low": float(r["Low"]),
                    "close": close,
                    "adjClose": float(r["Adj Close"]) if "Adj Close" in r else close,
                    "volume": float(r["Volume"]),
                }
            )
        except Exception:
            continue
    rows.reverse()  # yfinance is oldest-first; v3 contract is most-recent-first
    if days and days > 0:
        rows = rows[:days]
    return rows or None


def _yf_prefetch(symbols: list, days: int = 260) -> None:
    """Bulk-populate _yf_hist_cache via one threaded yfinance download.

    Sequential per-symbol fetches cost ~1.9s each (~16 min for the S&P 500).
    Entries land under the same (symbol, days) key _yf_fetch_history uses, so
    callers transparently hit cache. Failures stay uncached for per-symbol retry.
    """
    if not _yf_ok():
        return
    pending = [s for s in symbols if (s, days) not in _yf_hist_cache]
    if not pending:
        return
    import yfinance as yf

    period_days = max(int(days * 1.6) + 15, 400) if days else 400
    period = f"{period_days}d"
    yf_map = {_yf_sym(s): s for s in pending}
    chunk = 100
    tickers = list(yf_map.keys())
    for i in range(0, len(tickers), chunk):
        batch = tickers[i : i + chunk]
        try:
            data = yf.download(
                tickers=batch,
                period=period,
                auto_adjust=False,
                group_by="ticker",
                threads=True,
                progress=False,
            )
        except Exception:
            continue
        if data is None or data.empty:
            continue
        for yf_sym in batch:
            orig = yf_map[yf_sym]
            try:
                sub = data[yf_sym] if len(batch) > 1 else data
            except Exception:
                continue
            rows = _df_to_rows(sub, days)
            if rows:  # leave misses uncached so _yf_fetch_history can retry singly
                _yf_hist_cache[(orig, days)] = rows


def _yf_quote(symbols_str: str) -> Optional[list]:
    """Synthesize v3-style quote dicts from yfinance history, or None."""
    quotes = []
    for sym in symbols_str.split(","):
        sym = sym.strip()
        if not sym:
            continue
        rows = _yf_fetch_history(sym, 260)
        if not rows:
            continue
        highs = [r["high"] for r in rows]
        lows = [r["low"] for r in rows]
        vols = [r["volume"] for r in rows]
        quotes.append(
            {
                "symbol": sym,
                "price": rows[0]["close"],
                "yearHigh": max(highs) if highs else 0,
                "yearLow": min(lows) if lows else 0,
                "volume": vols[0] if vols else 0,
                "avgVolume": (sum(vols[:50]) / min(len(vols), 50)) if vols else 0,
                "marketCap": 0,
                "name": sym,
                "sector": "Unknown",
            }
        )
    return quotes or None


class FMPClient:
    """Client for Financial Modeling Prep API with rate limiting and caching"""

    BASE_URL = "https://financialmodelingprep.com/api/v3"
    RATE_LIMIT_DELAY = 0.3  # 300ms between requests

    _ENDPOINT_FAILURE_THRESHOLD = 9999  # never disable; 402s are per-ticker, not endpoint-wide

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("FMP_API_KEY")
        if not self.api_key:
            raise ValueError(
                "FMP API key required. Set FMP_API_KEY environment variable "
                "or pass api_key parameter."
            )
        self.session = requests.Session()
        self.session.headers.update({"apikey": self.api_key})
        self.cache = {}
        self.last_call_time = 0
        self.rate_limit_reached = False
        self.retry_count = 0
        self.max_retries = 1
        self.api_calls_made = 0
        # Circuit breaker: track consecutive failures per endpoint URL prefix
        self._endpoint_failures: dict[str, int] = {}
        self._disabled_endpoints: set[str] = set()
        # Most recent transport-level failure reason; set by _rate_limited_get
        # so _request_with_fallback can surface suppressed errors even when
        # an endpoint was called with quiet=True.
        self._last_error: Optional[str] = None

    def _rate_limited_get(
        self, url: str, params: Optional[dict] = None, quiet: bool = False
    ) -> Optional[dict]:
        self._last_error = None
        if self.rate_limit_reached:
            self._last_error = "daily rate limit already reached"
            return None

        if params is None:
            params = {}

        elapsed = time.time() - self.last_call_time
        if elapsed < self.RATE_LIMIT_DELAY:
            time.sleep(self.RATE_LIMIT_DELAY - elapsed)

        try:
            response = self.session.get(url, params=params, timeout=30)
            self.last_call_time = time.time()
            self.api_calls_made += 1

            if response.status_code == 200:
                self.retry_count = 0
                return response.json()
            elif response.status_code == 429:
                self.retry_count += 1
                if self.retry_count <= self.max_retries:
                    print("WARNING: Rate limit exceeded. Waiting 60 seconds...", file=sys.stderr)
                    time.sleep(60)
                    return self._rate_limited_get(url, params, quiet=quiet)
                else:
                    self._last_error = "HTTP 429 (daily rate limit)"
                    print("ERROR: Daily API rate limit reached.", file=sys.stderr)
                    self.rate_limit_reached = True
                    return None
            else:
                msg = f"HTTP {response.status_code} - {response.text[:200]}"
                self._last_error = msg
                if not quiet:
                    print(
                        f"ERROR: API request failed: {msg}",
                        file=sys.stderr,
                    )
                return None
        except requests.exceptions.RequestException as e:
            self._last_error = f"request exception: {e}"
            print(f"ERROR: Request exception: {e}", file=sys.stderr)
            return None

    def _request_with_fallback(self, endpoint_key, symbols_str, extra_params=None):
        """Try stable endpoint first, fall back to v3 for legacy users.

        Returns parsed JSON in v3-compatible shape, or None if all fail.
        Non-last endpoints are called with quiet=True so the user isn't
        alarmed by an expected stable failure when v3 will catch it — but
        when a non-last endpoint DOES fail, a WARN line is emitted explaining
        why we're falling back. Otherwise users only see the (often misleading)
        last-endpoint error and have no clue what really went wrong.
        """
        params = dict(extra_params) if extra_params else {}
        endpoints = _FMP_ENDPOINTS[endpoint_key]
        is_single = "," not in symbols_str

        for i, (base_url, url_builder) in enumerate(endpoints):
            # Circuit breaker: skip endpoints with too many consecutive failures
            if base_url in self._disabled_endpoints:
                continue

            url, final_params = url_builder(base_url, symbols_str, dict(params))
            is_last = i == len(endpoints) - 1
            data = self._rate_limited_get(url, final_params, quiet=not is_last)
            if not data:  # falsy (None, [], {}) — try next endpoint
                self._record_endpoint_failure(base_url)
                self._warn_fallback(base_url, is_last, self._last_error)
                continue

            # Normalize new stable EOD flat-list shape to v3-compatible dict.
            # No-op for v3 dict / historicalStockList responses.
            # `timeseries` (original request) is passed as `limit` so the
            # EOD endpoint's full-history response is truncated to the
            # legacy "most-recent N rows" contract.
            if endpoint_key == "historical":
                limit = params.get("timeseries") if isinstance(params, dict) else None
                data = _normalize_eod_flat_list(data, symbols_str, limit=limit)
                if not data:
                    self._record_endpoint_failure(base_url)
                    self._warn_fallback(
                        base_url,
                        is_last,
                        f"response had no rows matching '{symbols_str}'",
                    )
                    continue

            # Shape validation: reject truthy-but-wrong-shape responses
            valid = True
            shape_issue: Optional[str] = None
            if endpoint_key == "quote":
                if not isinstance(data, list) or len(data) == 0:
                    valid = False
                    shape_issue = "expected non-empty list"
                elif is_single and not any(
                    q.get("symbol", "").replace("-", ".") == symbols_str.replace("-", ".")
                    for q in data
                ):
                    valid = False
                    shape_issue = f"requested symbol '{symbols_str}' not in response"

            if endpoint_key == "historical":
                if not isinstance(data, dict):
                    valid = False
                    shape_issue = "expected dict"
                elif "historicalStockList" in data:
                    # stable batch format -> v3 single format (exact match only)
                    norm = symbols_str.replace("-", ".")
                    found = None
                    for entry in data["historicalStockList"]:
                        if entry.get("symbol", "").replace("-", ".") == norm:
                            found = {
                                "symbol": entry.get("symbol"),
                                "historical": entry.get("historical", []),
                            }
                            break
                    if found:
                        self._endpoint_failures[base_url] = 0
                        return found
                    valid = False
                    shape_issue = f"'{symbols_str}' not in historicalStockList"
                elif "historical" not in data:
                    valid = False
                    shape_issue = "missing 'historical' key"
                elif is_single and data.get("symbol"):
                    if data["symbol"].replace("-", ".") != symbols_str.replace("-", "."):
                        valid = False
                        shape_issue = (
                            f"response symbol '{data['symbol']}' != requested '{symbols_str}'"
                        )

            if valid:
                self._endpoint_failures[base_url] = 0
                return data
            self._record_endpoint_failure(base_url)
            self._warn_fallback(base_url, is_last, shape_issue or "unexpected response shape")
        return None

    def _warn_fallback(self, base_url: str, is_last: bool, reason: Optional[str]) -> None:
        """Emit a WARN line so users see why a non-last endpoint failed and the
        client is falling back. No-op when the failing endpoint is the last one
        (its error was already printed by _rate_limited_get with quiet=False)."""
        if is_last or not reason:
            return
        print(
            f"WARN: {base_url} failed ({reason}); falling back to next endpoint",
            file=sys.stderr,
        )

    def _record_endpoint_failure(self, base_url: str) -> None:
        """Track consecutive failures and disable endpoint after threshold."""
        failures = self._endpoint_failures.get(base_url, 0) + 1
        self._endpoint_failures[base_url] = failures
        if failures >= self._ENDPOINT_FAILURE_THRESHOLD:
            self._disabled_endpoints.add(base_url)

    def get_sp500_constituents(self) -> Optional[list[dict]]:
        """Fetch S&P 500 constituent list.

        Returns:
            List of dicts with keys: symbol, name, sector, subSector
            or None on failure.
        """
        cache_key = "sp500_constituents"
        if cache_key in self.cache:
            return self.cache[cache_key]

        # Migrate hardcoded v3 URL to /stable (this method bypasses the
        # _FMP_ENDPOINTS stable→v3 fallback list, so rewrite at the call site).
        url, params = v3_to_stable(f"{self.BASE_URL}/sp500_constituent")
        data = self._rate_limited_get(url, params)
        if data:
            self.cache[cache_key] = data
        return data

    def get_quote(self, symbols: str) -> Optional[list[dict]]:
        """Fetch real-time quote data for one or more symbols (comma-separated)"""
        cache_key = f"quote_{symbols}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._request_with_fallback("quote", symbols)
        if not data:  # FMP free-tier blocked -> yfinance fallback
            data = _yf_quote(symbols)
        if data:
            self.cache[cache_key] = data
        return data

    def get_batch_quotes(self, symbols: list[str]) -> dict[str, dict]:
        """Fetch quotes for a list of symbols, one per request (free-tier compatible)"""
        results = {}
        # _yf_quote synthesizes each quote from 260d of history; warm them in one
        # threaded download so the per-symbol loop below hits cache.
        _yf_prefetch(list(symbols), 260)
        batch_size = 1
        for i in range(0, len(symbols), batch_size):
            batch = symbols[i : i + batch_size]
            batch_str = ",".join(batch)
            quotes = self.get_quote(batch_str)
            if quotes:
                for q in quotes:
                    results[q["symbol"]] = q
        return results

    def get_batch_historical(self, symbols: list[str], days: int = 260) -> dict[str, list[dict]]:
        """Fetch historical prices for multiple symbols"""
        results = {}
        for symbol in symbols:
            data = self.get_historical_prices(symbol, days=days)
            if data and "historical" in data:
                results[symbol] = data["historical"]
        return results

    def calculate_sma(self, prices: list[float], period: int) -> float:
        """Calculate Simple Moving Average from a list of prices (most recent first)"""
        if len(prices) < period:
            return sum(prices) / len(prices)
        return sum(prices[:period]) / period

    def get_historical_prices(self, symbol: str, days: int = 365) -> Optional[dict]:
        """Fetch historical daily OHLCV data.

        Args:
            symbol: Stock symbol
            days: Number of trading days to fetch

        Returns:
            Dict with 'symbol' and 'historical' keys, where 'historical' is a
            list of price dicts (most-recent-first) with: date, open, high, low,
            close, adjClose, volume
        """
        cache_key = f"prices_{symbol}_{days}"
        if cache_key in self.cache:
            return self.cache[cache_key]

        data = self._request_with_fallback("historical", symbol, {"timeseries": days})
        if not data:  # FMP free-tier blocked -> yfinance fallback
            rows = _yf_fetch_history(symbol, days)
            if rows:
                data = {"symbol": symbol, "historical": rows}
        if data:
            self.cache[cache_key] = data
        return data

    def get_api_stats(self) -> dict:
        """Return API usage statistics."""
        return {
            "cache_entries": len(self.cache),
            "api_calls_made": self.api_calls_made,
            "rate_limit_reached": self.rate_limit_reached,
        }
